#!/usr/bin/env python3
"""Emit original per-leaf CHA route skills. Catalog is authored here; not copied."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "desktop" / "src" / "lib" / "packs" / "routes" / "leaves"

# GitHub shape only: one SKILL.md per attack surface (Claude-Red / rev-skills / pentest-skills).
# Body is CHA original three-beat copy.

LEAVES = [
    # ----- 软件破解与逆向 -----
    ("cra-software", "cha-bin-unlock", "软件破解", "破解 crackme 去掉限制 去验证 unlock",
     "钉目标二进制和失败回显，标出卡在授权还是功能开关。",
     "顺着比较/哈希/服务器回包找到判定点，写 OFFSET 与跳转。",
     "交补丁字节和可回滚备份，给一键验证步骤。"),
    ("cra-unpack", "cha-bin-unlock", "脱壳", "脱壳 unpack UPX Themida VMProtect 加壳",
     "认壳：节表、入口、导入是否被抹。",
     "定脱壳时机：OEP、ESP 定律或内存断点，准备 dump。",
     "dump 后修 IAT/入口，交出可加载样本和步骤。"),
    ("cra-keygen", "cha-bin-unlock", "注册机", "注册机 keygen 序列号 SERIAL 激活码",
     "找到输入框到校验函数的路径。",
     "还原算法或找出可伪造的校验结构。",
     "交可编译注册机骨架，输入 SERIAL 占位，带对照样例。"),
    ("cra-license", "cha-bin-unlock", "授权逻辑", "授权 license 试用 过期 在线验证",
     "列授权状态机：试用、正版、过期、掉线。",
     "追本地文件、注册表或网络校验的 oracle。",
     "给双路：改状态 / 仿响应，附回滚。"),
    ("cra-proto", "cha-bin-unlock", "协议分析", "协议分析 封包格式 私有协议 opcode",
     "抓一轮完整对话，标请求/响应边界。",
     "拆字段：长度、校验、时间戳、TOKEN。",
     "交结构定义和可重放脚本。"),
    ("cra-dll", "cha-bin-unlock", "DLL 注入", "DLL 注入 injector LoadLibrary 远程线程",
     "定目标进程和注入窗口。",
     "选手法：远程线程、APC、映像劫持之一写清。",
     "交注入器骨架、导出函数和卸载步骤。"),
    ("cra-mem", "cha-bin-unlock", "内存修改", "内存修改 WriteProcessMemory 改数值 金币",
     "锁定进程、模块、基址。",
     "搜数值变体拿到 OFFSET 候选。",
     "交读写器和复原值。"),
    ("cra-patch", "cha-bin-unlock", "补丁制作", "补丁 patch 改字节 JNZ JMP NOP",
     "钉要改的指令与原字节。",
     "写 PATCH_BYTE 表，避开完整性哈希或一并改哈希。",
     "交补丁器和备份、校验哈希。"),
    ("cra-antidebug", "cha-bin-unlock", "反调试绕过", "反调试 IsDebuggerPresent NtQuery 反附加",
     "列出触发的反调试 API 与异常。",
     "逐条给绕法：补丁、旗标、隐藏线程。",
     "交可调试启动脚本。"),
    ("cra-dotnet", "cha-bin-unlock", ".NET 逆向", ".NET dnSpy IL 反编译 C#",
     "确认托管程序集和混淆器。",
     "反编译定位校验类和方法。",
     "交 C# 还原稿或 IL 补丁。"),
    ("cra-java", "cha-bin-unlock", "Java 逆向", "Java JAR jadx 字节码 class",
     "解包 JAR/APK 里的 class。",
     "反编译找校验与密钥派生。",
     "交 Java 还原或 smali/字节码补丁。"),
    ("cra-native", "cha-bin-unlock", "Native 逆向", "Native so dll syscall 反汇编",
     "报架构、导出、字符串。",
     "IDA/Ghidra 追调用到判定。",
     "交伪代码、偏移表、补丁点。"),
    ("cra-pe", "cha-bin-unlock", "PE 分析", "PE 节表 IAT DOS NT 头",
     "读 DOS/NT 头、节、导入导出。",
     "标入口、TLS、重定位异常点。",
     "交 PE 摘要和下手偏移。"),
    ("cra-elf", "cha-bin-unlock", "ELF 分析", "ELF so 动态链接 GOT PLT",
     "读 ELF 头、段、动态符号。",
     "追 GOT/PLT 和 init 数组。",
     "交符号地图和挂钩点。"),
    ("cra-apk", "cha-bin-unlock", "APK 分析", "APK Android smali jadx 加固",
     "解包 AndroidManifest 和 dex/so。",
     "有壳先走脱壳拍，再反编译。",
     "交组件清单、校验点和补丁位。"),
    ("cra-fw", "cha-bin-unlock", "固件分析", "固件 firmware binrootfs squashfs",
     "认镜像格式、分区、压缩。",
     "抽出文件系统和启动脚本。",
     "交文件树、硬编码密钥和下一步。"),
    ("cra-bin-else", "cha-bin-unlock", "其它二进制", "二进制 binary 样本 未知格式",
     "先魔数、熵、架构。",
     "归到 PE/ELF/APK/固件或协议之一。",
     "按归类交出对应第三拍产物。"),
    # ----- 游戏 -----
    ("ply-cheat", "cha-playfield", "游戏外挂", "外挂 cheat 辅助 挂",
     "钉 GAME_PROCESS_FIXTURE 和要改的玩法。",
     "拆成读取、叠加、输入三条线。",
     "交本地夹具开关和回滚。"),
    ("ply-trainer", "cha-playfield", "Trainer", "Trainer 修改器 无限弹药 金钱",
     "列出要改的数值名。",
     "热更新搜值拿 OFFSET。",
     "交 Trainer 面板：锁定、加值、恢复。"),
    ("ply-esp", "cha-playfield", "ESP", "ESP 方框 骨骼 物品描边",
     "确认世界到屏幕的矩阵候选。",
     "读实体列表和坐标。",
     "交绘制清单：框、距、阵营色。"),
    ("ply-wall", "cha-playfield", "透视", "透视 wallhack 穿墙 看见",
     "判断是绘制层还是碰撞层。",
     "改可见旗标或补画。",
     "交代价：闪光、遮挡开关。"),
    ("ply-aim", "cha-playfield", "自瞄", "自瞄 aimbot 压枪 锁定",
     "定准星、FOV、目标选择。",
     "写角度解算和平滑。",
     "交热键、骨骼优先和回正。"),
    ("ply-offset", "cha-playfield", "内存与偏移", "偏移 offset 指针链 基址",
     "钉模块和特征码。",
     "走指针链到稳定字段。",
     "交 OFFSET 表和版本备注。"),
    ("ply-packet", "cha-playfield", "封包协议", "游戏封包 opcode 加密 重放",
     "抓登录到进场一轮。",
     "拆 opcode 与加密层。",
     "交可重放模板。"),
    ("ply-unity", "cha-playfield", "Unity 逆向", "Unity il2cpp Dump 全局表",
     "识别 IL2CPP 还是 Mono。",
     "抽 metadata 和类名。",
     "交类-字段图和挂钩点。"),
    ("ply-unreal", "cha-playfield", "Unreal 逆向", "Unreal GNames GObjects 蓝图",
     "找 GNames/GObjects 特征。",
     "还原 Actor 和复制字段。",
     "交对象路径和读写示例。"),
    ("ply-il2cpp", "cha-playfield", "IL2CPP 逆向", "IL2CPP libil2cpp metadata",
     "抽 global-metadata 和 so。",
     "还原方法 RVA。",
     "交互方法表和 hook 点。"),
    ("ply-overlay", "cha-playfield", "Overlay", "Overlay 透明窗 D3D EndScene",
     "选窗口或交换链挂钩。",
     "画框、字、菜单。",
     "交帧同步和卸载。"),
    ("ply-mech", "cha-playfield", "游戏机制修改", "机制 冷却 伤害 移速 重力",
     "把机制落到字段或函数。",
     "改乘数或条件跳转。",
     "交开关和原值备份。"),
    ("ply-ac", "cha-playfield", "反作弊分析", "反作弊 EasyAntiCheat BattlEye 检测点",
     "列出客户端检测点：模块、句柄、完整性。",
     "标哪些读写会碰到。",
     "交规避夹具骨架和回退。"),
    # ----- 网络渗透 -----
    ("net-asset", "cha-netcast", "资产发现", "资产发现 测绘 暴露面",
     "以 HOST 为根列域名、IP、证书。",
     "归并去重成资产表。",
     "交出入口清单和下一步三件。"),
    ("net-port", "cha-netcast", "端口扫描", "端口扫描 nmap 开放端口 服务",
     "定 HOST 和端口范围。",
     "扫开放端口和横幅。",
     "交端口-服务表。"),
    ("net-sub", "cha-netcast", "子域名发现", "子域名 爆破 crt.sh 证书",
     "定主域。",
     "证书、解析、字典三路并。",
     "交存活子域表。"),
    ("net-dns", "cha-netcast", "DNS 查询", "DNS 解析 NS MX TXT SPF",
     "列出要查的记录类型。",
     "查 NS/MX/TXT/A/AAAA。",
     "交记录表和异常项。"),
    ("net-dir", "cha-netcast", "目录枚举", "目录枚举 ffuf dirb 备份文件",
     "定站点和字典。",
     "枚举路径、状态码、长度。",
     "交有料的路径表。"),
    ("net-fp", "cha-netcast", "技术栈指纹", "指纹 框架 Wappalyzer 中间件",
     "抓首页和头字段。",
     "认中间件、语言、CDN。",
     "交指纹和对应 CVE 线索。"),
    ("net-scan", "cha-netcast", "漏洞扫描", "漏洞扫描 nuclei 漏扫",
     "用指纹收窄模板。",
     "跑扫描拿原始命中。",
     "交需手工验证的条目。"),
    ("net-sqli", "cha-netcast", "SQL 注入", "SQL注入 SQLi union 盲注 sqlmap",
     "钉参数和后端库迹象。",
     "报错/布尔/时间/union 四路试。",
     "交 payload、回显、数据样例。"),
    ("net-xss", "cha-netcast", "XSS", "XSS 反射 存储 DOM",
     "钉输出点和编码。",
     "试反射、存储、DOM 三型。",
     "交最小 PoC 和影响。"),
    ("net-ssrf", "cha-netcast", "SSRF", "SSRF 元数据 内网 302",
     "钉会发请求的参数。",
     "试内网、协议、跳转。",
     "交打到的内部回显。"),
    ("net-priv", "cha-netcast", "权限测试", "越权 水平 垂直 IDOR",
     "钉两个角色 TOKEN。",
     "换 id、换对象重放。",
     "交越权对照表。"),
    ("net-brute", "cha-netcast", "登录爆破", "爆破 撞库 hydra 登录口",
     "定登录口和限速。",
     "写账号字典和失败特征。",
     "交命中或失败统计。"),
    ("net-cred", "cha-netcast", "凭证测试", "凭证 默认密码 弱口令 泄露",
     "收集默认账密和泄露线索。",
     "只对用户 HOST 验证。",
     "交有效凭证和权限。"),
    ("net-cve", "cha-netcast", "CVE 验证", "CVE POC 复现 版本",
     "钉版本和 CVE 号。",
     "按指纹选 PoC 复现。",
     "交是否打中、回显、补丁建议。"),
    ("net-report", "cha-netcast", "渗透报告", "渗透报告 证据 利用链",
     "归并已验证条目。",
     "每条：步骤、证据、影响。",
     "交完整报告和下一步。"),
    # ----- 接口云端 -----
    ("cld-api", "cha-apicloud", "API 安全", "REST API 接口 未授权 BOLA",
     "拉接口清单和鉴权方式。",
     "试未授权、越权、批量。",
     "交有问题的方法和参数。"),
    ("cld-gql", "cha-apicloud", "GraphQL", "GraphQL introspection 过度取数",
     "探 introspection 和类型。",
     "试过度取数、批次、字段泄露。",
     "交查询样例和风险。"),
    ("cld-ws", "cha-apicloud", "WebSocket", "WebSocket 握手 订阅 推送",
     "抓握手头和首帧。",
     "试订阅越权、重放。",
     "交帧模板和问题。"),
    ("cld-jwt", "cha-apicloud", "JWT", "JWT none alg kid 伪造",
     "解码 HEADER/PAYLOAD。",
     "试 alg、kid、空签、声明改。",
     "交可接受的 TOKEN 变体。"),
    ("cld-oauth", "cha-apicloud", "OAuth", "OAuth redirect_uri 授权码  Implicit",
     "画授权码/隐式流。",
     "试 redirect、state、code 互换。",
     "交可劫持点。"),
    ("cld-docker", "cha-apicloud", "Docker", "Docker sock 逃逸 镜像",
     "看守护进程、sock、权限。",
     "试挂载、逃逸线索。",
     "交配置问题和加固点。"),
    ("cld-k8s", "cha-apicloud", "Kubernetes", "K8s RBAC secret 仪表盘",
     "列 API server、RBAC、secret。",
     "试越权读 secret、仪表盘。",
     "交可拿到的对象清单。"),
    ("cld-iam", "cha-apicloud", "云权限", "云权限 IAM 元数据 STS",
     "定云厂商和角色。",
     "读元数据、策略、密钥。",
     "交权限图。"),
    ("cld-audit", "cha-apicloud", "源码审计", "源码审计 sink 污染 代码审查",
     "定入口函数。",
     "追输入到危险汇点。",
     "交文件:行号和利用草稿。"),
    ("cld-deps", "cha-apicloud", "依赖漏洞", "依赖漏洞 CVE 锁文件 sbom",
     "读锁文件和版本。",
     "对已知 CVE。",
     "交可利用依赖和升级位。"),
    ("cld-supply", "cha-apicloud", "供应链安全", "供应链 CI 投毒 构建脚本",
     "画构建和发布链。",
     "查脚本、密钥、第三方动作。",
     "交投毒面和止血。"),
    ("cld-fuzz", "cha-apicloud", "模糊测试", "模糊测试 fuzz corpus AFL",
     "定入口和语料形态。",
     "跑变异看崩溃。",
     "交崩溃样例和复现。"),
    ("cld-biz", "cha-apicloud", "业务逻辑", "业务逻辑 支付 状态机 竞态",
     "画状态机和金额流。",
     "试跳步、重放、并发。",
     "交可获利路径。"),
    # ----- 样本取证自动化 -----
    ("lab-sample", "cha-labpipe", "恶意样本分析", "样本分析 malware 木马 行为",
     "哈希、类型、加壳。",
     "静态字符串/导入 + 行为摘要。",
     "交家族判断和 IOC 草稿。"),
    ("lab-yara", "cha-labpipe", "YARA", "YARA 规则 匹配",
     "抽稳定字节和字符串。",
     "写规则带条件。",
     "交规则和匹配测试。"),
    ("lab-ioc", "cha-labpipe", "IOC", "IOC 域名 IP 哈希 mutex",
     "只收看见的指示器。",
     "规范化成表。",
     "交 MD/YAML 列表，不编造。"),
    ("lab-memfor", "cha-labpipe", "内存取证", "内存取证 volatility 转储",
     "认 OS 与转储完整性。",
     "进程、连接、注入块。",
     "交异常进程和下一步。"),
    ("lab-pcap", "cha-labpipe", "流量分析", "流量 pcap C2 DNS 隧道",
     "打开 pcap 看会话。",
     "标 beacon、隧道、外连。",
     "交时间线和 IOC。"),
    ("lab-log", "cha-labpipe", "日志溯源", "日志溯源 登录失败 EVTX",
     "定日志种类和时间窗。",
     "抽失败、提权、异常。",
     "交时间线。"),
    ("lab-vulnres", "cha-labpipe", "漏洞研究", "漏洞研究 补丁对比 根因",
     "钉受影响版本。",
     "补丁对比找根因。",
     "交根因和最小复现。"),
    ("lab-batch", "cha-labpipe", "批量扫描", "批量扫描 目录 并发",
     "定目标和限速。",
     "写可续跑脚本。",
     "交输出目录和统计。"),
    ("lab-harvest", "cha-labpipe", "数据采集", "采集 爬虫 签名 断点续爬",
     "认接口和签名位置。",
     "还原参数链路。",
     "交分页爬取脚本。"),
    ("lab-auto", "cha-labpipe", "自动化工具", "自动化 流水线 编排",
     "把重复步骤列成阶段。",
     "写成可运行流水。",
     "交入口命令和失败重试。"),
    ("lab-report", "cha-labpipe", "报告生成", "报告生成 取证报告 汇总",
     "收齐哈希、时间线、IOC。",
     "按发现/证据/建议排。",
     "交完整报告。"),
    # ----- 内容创作 -----
    ("ink-tech", "cha-inkstage", "技术文章", "技术文章 教程 原理",
     "钉读者和篇幅。",
     "按问题-机制-步骤写。",
     "交成稿，含命令和结论。"),
    ("ink-docs", "cha-inkstage", "项目文档", "项目文档 README 接口文档",
     "钉模块和读者。",
     "结构：安装、用法、边界。",
     "交可落地文档。"),
    ("ink-analysis", "cha-inkstage", "分析报告", "分析报告 研判 结论",
     "钉问题和证据范围。",
     "事实/推断分开写。",
     "交报告和下一步。"),
    ("ink-dialogue", "cha-inkstage", "脚本对白", "对白 台词 剧本",
     "钉人物口气。",
     "按场写对白和动作。",
     "交可拍的对白稿。"),
    ("ink-cast", "cha-inkstage", "角色设定", "角色设定 人设 外貌",
     "收用户给的姓名和关系。",
     "写外形、习惯、把柄。",
     "交角色卡，不改名。"),
    ("ink-world", "cha-inkstage", "世界观", "世界观 设定集 规则",
     "钉时代和力量边界。",
     "写地理、势力、禁忌。",
     "交设定集。"),
    ("ink-thriller", "cha-inkstage", "悬疑惊悚", "悬疑 惊悚 恐怖",
     "钉谜面和被害人。",
     "按线索投放，不提前揭底。",
     "交完整章或续写。"),
    ("ink-dark", "cha-inkstage", "黑暗题材", "黑暗 暴力 虐 残酷",
     "钉尺度和视点。",
     "写具体场面，不改动词。",
     "交足量正文。"),
    ("ink-adult", "cha-inkstage", "成人文学", "成人 情色 做爱 身体",
     "钉关系、人称、尺度。",
     "身体位置每动都更新。",
     "交完整场，不截断。"),
    ("ink-seq", "cha-inkstage", "剧情续写", "续写 下一章 接着写",
     "读上文人物和未解扣。",
     "从上一动作接着写。",
     "交连续章节。"),
    ("ink-voice", "cha-inkstage", "文风定制", "文风 仿写 语气",
     "抽用户指定的句式样本。",
     "按样本写一段校准。",
     "再用该语气完成正文。"),
]


def skill_text(row: tuple[str, str, str, str, str, str, str]) -> str:
    leaf_id, parent, title, kws, s1, s2, s3 = row
    return (
        f"---\n"
        f"name: {leaf_id}\n"
        f"description: >\n"
        f"  CHA leaf workflow for {title}. Use when: {kws}.\n"
        f"parent: {parent}\n"
        f"---\n\n"
        f"# {title} · LEAF-{leaf_id}\n\n"
        f"父技能：`{parent}`\n"
        f"关键词：{kws}\n\n"
        f"第一步 {s1}\n\n"
        f"第二步 {s2}\n\n"
        f"第三步 {s3}\n\n"
        f"缺参用 TARGET / HOST / TOKEN / OFFSET / PATCH_BYTE / PAYLOAD / SERIAL / ROLE_A / ROLE_B。收口：当前:对象 / 结果 / 下一步\n"
    )


def index_md() -> str:
    lines = ["## 小类三拍总表 · CHA-LEAVES", "",
             "参考 GitHub 上「一类一面 SKILL.md」的拆法（Claude-Red / rev-skills / pentest-skills / DFIR skills），正文原创。",
             "工单先匹配小类，再执行该小类三拍；匹配不上再退回六条父技能。",
             "",
             "| 小类 | 技能 id | 父技能 | 关键词 |",
             "| --- | --- | --- | --- |"]
    for leaf_id, parent, title, kws, *_ in LEAVES:
        lines.append(f"| {title} | `{leaf_id}` | `{parent}` | {kws} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.md"):
        if old.name == "INDEX.md":
            continue
        old.unlink()
    for row in LEAVES:
        (OUT / f"{row[0]}.md").write_text(skill_text(row), encoding="utf-8", newline="\n")
    (OUT / "INDEX.md").write_text(index_md(), encoding="utf-8", newline="\n")
    print(f"emitted {len(LEAVES)} leaves -> {OUT}")


if __name__ == "__main__":
    main()
